name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: https://gurukulsetu.com/api/v1

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build project
      - name: Build Project
        run: npm run build

      # 5. Copy dist folder to server
      - name: SCP Transfer
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'dist/**'
          target: '/var/www/school-management-system-frontend/dist'

      # 6. SSH into server & restart PM2
      - name: Restart nginx on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            systemctl reload nginx.service
